In [1]:
import pandas as pd
import seaborn as sns

In [2]:
# charger le dataset
df = pd.read_csv('diabetes_dataset__2019.csv')
df

,Age,Gender,Family_Diabetes,highBP,PhysicallyActive,BMI,Smoking,Alcohol,Sleep,SoundSleep,RegularMedicine,JunkFood,Stress,BPLevel,Pregancies,Pdiabetes,UriationFreq,Diabetic
0,50-59,Male,no,yes,one hr or more,39.0,no,no,8,6,no,occasionally,sometimes,high,0.0,0,not much,no
1,50-59,Male,no,yes,less than half an hr,28.0,no,no,8,6,yes,very often,sometimes,normal,0.0,0,not much,no
2,40-49,Male,no,no,one hr or more,24.0,no,no,6,6,no,occasionally,sometimes,normal,0.0,0,not much,no
3,50-59,Male,no,no,one hr or more,23.0,no,no,8,6,no,occasionally,sometimes,normal,0.0,0,not much,no
4,40-49,Male,no,no,less than half an hr,27.0,no,no,8,8,no,occasionally,sometimes,normal,0.0,0,not much,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947,less than 40,Male,yes,no,more than half an hr,25.0,no,no,8,6,no,often,sometimes,normal,0.0,0,not much,yes
948,60 or older,Male,yes,yes,more than half an hr,27.0,no,no,6,5,yes,occasionally,sometimes,high,0.0,0,quite often,yes
949,60 or older,Male,no,yes,none,23.0,no,no,6,5,yes,occasionally,sometimes,high,0.0,0,not much,no
950,60 or older,Male,no,yes,less than half an hr,27.0,no,yes,6,5,yes,occasionally,very often,high,0.0,0,not much,no
951,60 or older,Female,yes,yes,one hr or more,30.0,no,no,7,4,yes,occasionally,sometimes,high,2.0,0,quite often,yes

In [3]:
df.describe()

              BMI       Sleep  SoundSleep  Pregancies
count  948.000000  952.000000  952.000000  910.000000
mean    25.763713    6.949580    5.495798    0.386813
std      5.402595    1.273189    1.865618    0.909455
min     15.000000    4.000000    0.000000    0.000000
25%     22.000000    6.000000    4.000000    0.000000
50%     25.000000    7.000000    6.000000    0.000000
75%     29.000000    8.000000    7.000000    0.000000
max     45.000000   11.000000   11.000000    4.000000

In [4]:
# identifier les colonnes avec les valuers manquantes
df.isnull().sum()

Age                  0
Gender               0
Family_Diabetes      0
highBP               0
PhysicallyActive     0
BMI                  4
Smoking              0
Alcohol              0
Sleep                0
SoundSleep           0
RegularMedicine      0
JunkFood             0
Stress               0
BPLevel              0
Pregancies          42
Pdiabetes            1
UriationFreq         0
Diabetic             1
dtype: int64

In [5]:
# Utiliser l'imputation par la mÃ©diane pour les variables numÃ©riques.
df.fillna(df.median(numeric_only=True), inplace=True)

In [6]:
# Utiliser l'imputation par le mode pour les variables catÃ©gorielles.
df['Pdiabetes'].fillna(df['Pdiabetes'].mode()[0], inplace=True)

In [7]:
df['Diabetic'].fillna(df['Diabetic'].mode()[0], inplace=True)

In [8]:
# verifier s'il existe encore des valeurs manquantes
df.isnull().sum()

Age                 0
Gender              0
Family_Diabetes     0
highBP              0
PhysicallyActive    0
BMI                 0
Smoking             0
Alcohol             0
Sleep               0
SoundSleep          0
RegularMedicine     0
JunkFood            0
Stress              0
BPLevel             0
Pregancies          0
Pdiabetes           0
UriationFreq        0
Diabetic            0
dtype: int64